print ("Las máquinas me sorprenden con mucha frecuencia.")
print()
print("Aguante River Plate")
print(23)
print("Una computadora puede ser llamada \"inteligiente\" si logra engañar a una persona haciéndole creer que es humano.")
print("texto \"Destacado\" sigue con el texto")
print('texto "Destacado" sigue con el texto')
print (6%5)